"""Hang so trich tu 'OCB_DBX_ZONEC - Technical_Document_v1.1' muc III.4.2
(Quy tac khi xu li cac bang tu Silver). Sua tai lieu -> sua file nay.
"""
from __future__ import annotations

# --- muc "Cac truong hop dac biet": bang transaction PHAI loc source_event_date = :DATADT
# (khong phai <=). Nguon: tai lieu para 208-258 (49 bang) + toolS/gold_review/docs/
# table_deltaload_phase1 1.xlsx sheet 'RV DELTALOAD append' (cot 'Ten bang raw_vault',
# ~210 bang nap kieu APPEND = phat sinh moi hang ngay = transaction). Doi chieu 2 nguon
# nay khop 209/210 dong Excel; thieu "effsat_link_xl_pdtd_link" da bo sung o day.
TRANSACTION_SATS = {
    "effsat_link_crb_branch", "effsat_link_crb_customer",
    "effsat_link_invoice_log_doc", "effsat_link_td_auth_sch_acnt_contract",
    "effsat_link_xl_pdtd_link",
    "effsat_link_user_notification", "hub_audit_message",
    "hub_balance", "hub_categ_entry",
    "hub_clearing_citad", "hub_clevertap_tracking",
    "hub_crb", "hub_credit_card_registration",
    "hub_data_sharing_consent", "hub_funds_transfer",
    "hub_giao_dich", "hub_gl_trace",
    "hub_invoice_log", "hub_line_movement_toanhang",
    "hub_m_transaction", "hub_message",
    "hub_notification", "hub_onboarding",
    "hub_party", "hub_payment",
    "hub_payment_history", "hub_payment_order",
    "hub_pdtd_nhom_giao_dich", "hub_re_consol_spec_entry",
    "hub_service", "hub_stmt_entry",
    "hub_td_auth_sch", "hub_teller",
    "hub_transfer_bill", "hub_tsbd_giaodich_chinh",
    "hub_tsbd_tai_san", "hub_usage_action",
    "link_audit_message_device", "link_audit_message_user",
    "link_balance_acnt_contract", "link_categ_entry_branch",
    "link_categ_entry_customer", "link_clevertap_tracking_customer",
    "link_crb_account", "link_crb_branch",
    "link_crb_customer", "link_crb_loans",
    "link_crb_loans_payment_due", "link_credit_card_registration_bpm",
    "link_credit_card_registration_customer", "link_data_sharing_consent_customer",
    "link_doc_m_transaction", "link_entry_item",
    "link_funds_transfer_branch", "link_funds_transfer_clearing_citad",
    "link_funds_transfer_credit_account", "link_funds_transfer_credit_customer",
    "link_funds_transfer_debit_account", "link_funds_transfer_debit_customer",
    "link_giao_dich_khach_hang", "link_gl_trace_credit_entry",
    "link_gl_trace_debit_entry", "link_invoice_log_acnt_contract",
    "link_invoice_log_doc", "link_item_account_w4",
    "link_item_templ_approved", "link_line_movement_toanhang_categ_entry",
    "link_line_movement_toanhang_re_consol_spec_entry", "link_line_movement_toanhang_stmt_entry",
    "link_message_user", "link_onboarding_appflyer",
    "link_onboarding_customer", "link_party_user",
    "link_payment_acnt_contract", "link_payment_history_funds_transfer",
    "link_payment_history_payment_order", "link_payment_history_user",
    "link_payment_m_transaction", "link_payment_order_funds_transfer",
    "link_payment_order_hierarchy", "link_payment_order_user",
    "link_pdtd_nhom_giao_dich_khach_hang", "link_re_consol_spec_entry_branch",
    "link_re_consol_spec_entry_customer", "link_re_consol_spec_entry_officer",
    "link_service_customer", "link_stmt_entry_branch",
    "link_stmt_entry_customer", "link_stmt_entry_officer",
    "link_td_auth_sch_acnt_contract", "link_td_auth_sch_client",
    "link_teller_account1", "link_teller_account2",
    "link_teller_branch", "link_teller_customer1",
    "link_teller_customer2", "link_transfer_bill_account",
    "link_transfer_bill_customer", "link_transfer_bill_funds_transfer",
    "link_transfer_bill_payment_order", "link_tsbd_giaodich_chinh_khach_hang",
    "link_usage_action_acnt_contract", "link_usage_action_document",
    "link_user_notification", "link_xl_pdtd_link",
    "non_his_sat_in_app_events_device", "non_his_sat_in_app_events_event",
    "non_his_sat_organic_in_app_events_device", "non_his_sat_organic_in_app_events_event",
    "sat_account_balance", "sat_audit_message_device",
    "sat_audit_message_emulator", "sat_audit_message_information",
    "sat_balance_information", "sat_balance_instalment",
    "sat_balance_interest_fee", "sat_balance_principal",
    "sat_categ_entry_audit", "sat_categ_entry_classification",
    "sat_categ_entry_information", "sat_clevertap_tracking_detail",
    "sat_crb_balance", "sat_crb_information",
    "sat_credit_card_registration_customer_info", "sat_credit_card_registration_financial_profile",
    "sat_credit_card_registration_flow", "sat_credit_card_registration_information",
    "sat_credit_card_registration_introduce", "sat_credit_card_registration_other",
    "sat_data_sharing_consent_information", "sat_data_sharing_consent_other",
    "sat_funds_transfer_account", "sat_funds_transfer_fee",
    "sat_funds_transfer_information", "sat_funds_transfer_other",
    "sat_funds_transfer_party", "sat_funds_transfer_system",
    "sat_giao_dich_tdcn_tai_san_bao_dam", "sat_giao_dich_tdcn_thong_tin_chung",
    "sat_giao_dich_tdcn_xl_gdtd", "sat_giao_dich_tdtc_nghiep_vu_xl_gdtd",
    "sat_giao_dich_tdtc_thong_tin_chung", "sat_giao_dich_tdtc_thong_tin_to_trinh",
    "sat_giao_dich_thong_tin_chung", "sat_giao_dich_tht_nhom_chinh_sach_the",
    "sat_giao_dich_tsbd", "sat_giaodich_sla",
    "sat_gl_trace_credit", "sat_gl_trace_debit",
    "sat_gl_trace_information", "sat_h_pdtd_gdich_ctiet_pduyet",
    "sat_h_pdtd_gdich_lsu_pduyet", "sat_invoice_log_detail",
    "sat_invoice_log_information", "sat_item_balance_rate",
    "sat_item_information", "sat_lich_su_giao_dich",
    "sat_line_movement_toanhang", "sat_link_xl_pdtd_link",
    "sat_message_information", "sat_notification",
    "sat_notification_information", "sat_omni_customer_information",
    "sat_onboarding_information", "sat_party_account_information",
    "sat_party_account_other", "sat_party_business",
    "sat_party_classification", "sat_party_information",
    "sat_party_other", "sat_payment_amount",
    "sat_payment_history_information", "sat_payment_history_other",
    "sat_payment_information", "sat_payment_order_classification",
    "sat_payment_order_information", "sat_payment_order_schedule",
    "sat_payment_principal", "sat_pdtd_giao_dich_tin_dung",
    "sat_pdtd_nhom_giao_dich_han_muc", "sat_pdtd_nhom_giao_dich_ho_so",
    "sat_pdtd_nhom_giao_dich_phe_duyet", "sat_pdtd_nhom_giao_dich_sla",
    "sat_pdtd_nhom_giao_dich_tham_dinh", "sat_pdtd_nhom_giao_dich_trang_thai",
    "sat_pdtd_san_pham", "sat_re_consol_spec_entry_audit",
    "sat_re_consol_spec_entry_classification", "sat_re_consol_spec_entry_information",
    "sat_service_audit", "sat_service_information",
    "sat_service_package", "sat_stmt_entry_audit",
    "sat_stmt_entry_classification", "sat_stmt_entry_information",
    "sat_td_auth_sch_information", "sat_teller_information",
    "sat_teller_other", "sat_teller_vat",
    "sat_transfer_bill_amount", "sat_transfer_bill_information",
    "sat_transfer_bill_other", "sat_transfer_bill_response",
    "sat_tsbd_giaodich_chi_tiet", "sat_tsbd_giaodich_chinh_khoi_tao_phe_duyet",
    "sat_tsbd_giaodich_chinh_thong_tin_chung", "sat_tsbd_giaodich_chinh_thong_tin_dinh_gia",
    "sat_tsbd_giaodich_lich_su_v2", "sat_tsbd_tai_san_phuong_tien",
    "sat_tsbd_tai_san_thong_tin_chung", "sat_tsbd_tai_san_thong_tin_khac",
    "sat_usage_action_date", "sat_usage_action_information",
    "sat_usage_action_state", "sts_hub_crb",
    # --- bo sung thieu: nguon T24_RE_STAT_LINE_BAL va T24_PC_RE_STAT_LINE_BAL
    # (bang statement/balance movement, phat sinh hang ngay = transaction).
    # Chua doi chieu lai voi tai lieu/Excel goc (xem comment dau file) - can tim hieu
    # lai trong tuong lai de xac nhan co thuoc danh sach 49 bang transaction hay khong.
    "hub_re_stat_line_bal", "sat_re_stat_line_bal",
    "hub_pc_re_stat_line_bal", "sat_pc_re_stat_line_bal",
    # --- bo sung thieu: bang business_vault csat_crb_balance va csat_customer_sum_balance
    # la bang transaction -> phai dung source_event_date = :DATADT. Chua doi chieu lai voi
    # tai lieu/Excel goc (xem comment dau file) - can tim hieu lai trong tuong lai.
    "csat_crb_balance", "csat_customer_sum_balance",
}

# --- muc PIT: PIT da bao gom hieu luc, LEFT JOIN thang PIT voi sat la du
PIT_SELF_SUFFICIENT = {
    "pit_loan": {"hub_loans", "sat_loans_information", "sat_loans_classification",
                 "sat_loans_rate", "sat_loans_terms"},
    "pit_customer": {"hub_customer", "sat_customer_information",
                     "sat_customer_extra_information", "sat_customer_contact",
                     "sat_customer_classification", "sat_customer_kyc",
                     "sat_customer_financial_statement", "sat_cust_package"},
}

# --- muc PIT (luu y): dung PIT nhung VAN phai join sts_hub de loc ban ghi co hieu luc
PIT_NEEDS_STS = {
    "pit_account": {"hub_account", "sat_account_balance", "sat_account_information",
                    "sat_account_classification", "sat_deposits_rate",
                    "sat_deposits_information", "sat_deposits_terms"},
    "pit_acnt_contract": {"hub_acnt_contract", "sat_acnt_contract_information",
                          "sat_acnt_contract_cs_status_log", "sat_acnt_contract_other",
                          "sat_acnt_contract_add_data", "sat_acnt_contract_type"},
}

PIT_ENTITY_OF_SAT = {sat: pit for group in (PIT_SELF_SUFFICIENT, PIT_NEEDS_STS)
                     for pit, sats in group.items() for sat in sats}
