-- ============================================================
-- Source  : .appsflyer.organic_in_app_events_report
-- Targets : hub_appsflyer
--           non_his_sat_organic_in_app_events_event
--           non_his_sat_organic_in_app_events_device
-- Range   : 20250101 -> 20250131
-- Khớp model non_his_satellite (non_his): minus theo dòng (EXCEPT ALL, bỏ load_timestamp) => chỉ chèn phần thêm/thiếu, chạy lại cùng ngày không nhân đôi.
-- ============================================================
DROP TEMPORARY TABLE IF EXISTS tmp_organic_in_app_events_report; CREATE TEMPORARY TABLE tmp_organic_in_app_events_report AS
SELECT
    sha2(COALESCE(UPPER(TRIM(CAST(appsflyer_id AS string))), ''), 256) AS appsflyer_hashkey,
    to_date(regexp_replace(substr(event_time, 1, 10), '-', ''), 'yyyyMMdd') AS source_event_date,
    appsflyer_id,
    install_time, event_time, event_name, event_value, event_revenue, event_revenue_currency,
    event_revenue_usd, event_source, is_receipt_validated, attributed_touch_type, attributed_touch_time,
    partner, media_source, channel, keywords, campaign, campaign_id, adset, adset_id, ad, ad_id, ad_type,
    site_id, sub_site_id, sub_param_1, sub_param_2, sub_param_3, sub_param_4, sub_param_5,
    carrier, cost_model, cost_value, cost_currency,
    contributor_1_partner, contributor_1_media_source, contributor_1_campaign, contributor_1_touch_type, contributor_1_touch_time,
    contributor_2_partner, contributor_2_media_source, contributor_2_campaign, contributor_2_touch_type, contributor_2_touch_time,
    contributor_3_partner, contributor_3_media_source, contributor_3_campaign, contributor_3_touch_type, contributor_3_touch_time,
    is_retargeting, retargeting_conversion_type, attribution_lookback, reengagement_window, is_primary_attribution,
    city, wifi, operator, language, advertising_id, idfa, android_id, customer_user_id, imei, idfv,
    platform, device_type, os_version, app_version, sdk_version, app_id, app_name, bundle_id,
    country_code, dma, ip, postal_code, region, state, user_agent, http_referrer, original_url
FROM IDENTIFIER({{catalog_sourcing}} || '.appsflyer.organic_in_app_events_report')
WHERE regexp_replace(substr(event_time, 1, 10), '-', '') BETWEEN {{start_date}} AND {{end_date}}
  AND appsflyer_id IS NOT NULL;

-- [hub_appsflyer] Moved to installs_report.sql (consolidated UNION ALL to avoid Delta version conflicts)

-- Satellite: non_his_organic_in_app_events_report_event (append toàn bộ dòng, khớp model)
INSERT INTO IDENTIFIER({{catalog_cleaned}} || '.raw_vault.non_his_sat_organic_in_app_events_event')
(appsflyer_hashkey, source_event_date, load_timestamp, record_source,
 install_time, event_time, event_name, event_value, event_revenue, event_revenue_currency,
 event_revenue_usd, event_source, is_receipt_validated, attributed_touch_type, attributed_touch_time,
 partner, media_source, channel, keywords, campaign, campaign_id, adset, adset_id, ad, ad_id, ad_type,
 site_id, sub_site_id, sub_param_1, sub_param_2, sub_param_3, sub_param_4, sub_param_5,
 carrier, cost_model, cost_value, cost_currency,
 contributor_1_partner, contributor_1_media_source, contributor_1_campaign, contributor_1_touch_type, contributor_1_touch_time,
 contributor_2_partner, contributor_2_media_source, contributor_2_campaign, contributor_2_touch_type, contributor_2_touch_time,
 contributor_3_partner, contributor_3_media_source, contributor_3_campaign, contributor_3_touch_type, contributor_3_touch_time,
 is_retargeting, retargeting_conversion_type, attribution_lookback, reengagement_window, is_primary_attribution)
WITH src AS (
    SELECT
        appsflyer_hashkey,
        source_event_date,
        install_time,
        event_time,
        event_name,
        event_value,
        event_revenue,
        event_revenue_currency,
        event_revenue_usd,
        event_source,
        is_receipt_validated,
        attributed_touch_type,
        attributed_touch_time,
        partner,
        media_source,
        channel,
        keywords,
        campaign,
        campaign_id,
        adset,
        adset_id,
        ad,
        ad_id,
        ad_type,
        site_id,
        sub_site_id,
        sub_param_1,
        sub_param_2,
        sub_param_3,
        sub_param_4,
        sub_param_5,
        carrier,
        cost_model,
        cost_value,
        cost_currency,
        contributor_1_partner,
        contributor_1_media_source,
        contributor_1_campaign,
        contributor_1_touch_type,
        contributor_1_touch_time,
        contributor_2_partner,
        contributor_2_media_source,
        contributor_2_campaign,
        contributor_2_touch_type,
        contributor_2_touch_time,
        contributor_3_partner,
        contributor_3_media_source,
        contributor_3_campaign,
        contributor_3_touch_type,
        contributor_3_touch_time,
        is_retargeting,
        retargeting_conversion_type,
        attribution_lookback,
        reengagement_window,
        is_primary_attribution
    FROM tmp_organic_in_app_events_report
),
delta AS (
    SELECT * FROM src
    EXCEPT ALL
    SELECT
        appsflyer_hashkey,
        source_event_date,
        install_time,
        event_time,
        event_name,
        event_value,
        event_revenue,
        event_revenue_currency,
        event_revenue_usd,
        event_source,
        is_receipt_validated,
        attributed_touch_type,
        attributed_touch_time,
        partner,
        media_source,
        channel,
        keywords,
        campaign,
        campaign_id,
        adset,
        adset_id,
        ad,
        ad_id,
        ad_type,
        site_id,
        sub_site_id,
        sub_param_1,
        sub_param_2,
        sub_param_3,
        sub_param_4,
        sub_param_5,
        carrier,
        cost_model,
        cost_value,
        cost_currency,
        contributor_1_partner,
        contributor_1_media_source,
        contributor_1_campaign,
        contributor_1_touch_type,
        contributor_1_touch_time,
        contributor_2_partner,
        contributor_2_media_source,
        contributor_2_campaign,
        contributor_2_touch_type,
        contributor_2_touch_time,
        contributor_3_partner,
        contributor_3_media_source,
        contributor_3_campaign,
        contributor_3_touch_type,
        contributor_3_touch_time,
        is_retargeting,
        retargeting_conversion_type,
        attribution_lookback,
        reengagement_window,
        is_primary_attribution
    FROM IDENTIFIER({{catalog_cleaned}} || '.raw_vault.non_his_sat_organic_in_app_events_event')
    WHERE source_event_date BETWEEN to_date({{start_date}}, 'yyyyMMdd') AND to_date({{end_date}}, 'yyyyMMdd')
)
SELECT
    d.appsflyer_hashkey AS appsflyer_hashkey,
    d.source_event_date AS source_event_date,
    current_timestamp() AS load_timestamp,
    'appsflyer__organic_in_app_events_report' AS record_source,
    d.install_time AS install_time,
    d.event_time AS event_time,
    d.event_name AS event_name,
    d.event_value AS event_value,
    d.event_revenue AS event_revenue,
    d.event_revenue_currency AS event_revenue_currency,
    d.event_revenue_usd AS event_revenue_usd,
    d.event_source AS event_source,
    d.is_receipt_validated AS is_receipt_validated,
    d.attributed_touch_type AS attributed_touch_type,
    d.attributed_touch_time AS attributed_touch_time,
    d.partner AS partner,
    d.media_source AS media_source,
    d.channel AS channel,
    d.keywords AS keywords,
    d.campaign AS campaign,
    d.campaign_id AS campaign_id,
    d.adset AS adset,
    d.adset_id AS adset_id,
    d.ad AS ad,
    d.ad_id AS ad_id,
    d.ad_type AS ad_type,
    d.site_id AS site_id,
    d.sub_site_id AS sub_site_id,
    d.sub_param_1 AS sub_param_1,
    d.sub_param_2 AS sub_param_2,
    d.sub_param_3 AS sub_param_3,
    d.sub_param_4 AS sub_param_4,
    d.sub_param_5 AS sub_param_5,
    d.carrier AS carrier,
    d.cost_model AS cost_model,
    d.cost_value AS cost_value,
    d.cost_currency AS cost_currency,
    d.contributor_1_partner AS contributor_1_partner,
    d.contributor_1_media_source AS contributor_1_media_source,
    d.contributor_1_campaign AS contributor_1_campaign,
    d.contributor_1_touch_type AS contributor_1_touch_type,
    d.contributor_1_touch_time AS contributor_1_touch_time,
    d.contributor_2_partner AS contributor_2_partner,
    d.contributor_2_media_source AS contributor_2_media_source,
    d.contributor_2_campaign AS contributor_2_campaign,
    d.contributor_2_touch_type AS contributor_2_touch_type,
    d.contributor_2_touch_time AS contributor_2_touch_time,
    d.contributor_3_partner AS contributor_3_partner,
    d.contributor_3_media_source AS contributor_3_media_source,
    d.contributor_3_campaign AS contributor_3_campaign,
    d.contributor_3_touch_type AS contributor_3_touch_type,
    d.contributor_3_touch_time AS contributor_3_touch_time,
    d.is_retargeting AS is_retargeting,
    d.retargeting_conversion_type AS retargeting_conversion_type,
    d.attribution_lookback AS attribution_lookback,
    d.reengagement_window AS reengagement_window,
    d.is_primary_attribution AS is_primary_attribution
FROM delta d;

-- Satellite: non_his_organic_in_app_events_report_device (append toàn bộ dòng, khớp model)
INSERT INTO IDENTIFIER({{catalog_cleaned}} || '.raw_vault.non_his_sat_organic_in_app_events_device')
(appsflyer_hashkey, source_event_date, load_timestamp, record_source,
 city, wifi, operator, language, advertising_id, idfa, android_id, customer_user_id, imei, idfv,
 platform, device_type, os_version, app_version, sdk_version, app_id, app_name, bundle_id,
 country_code, dma, ip, postal_code, region, state, user_agent, http_referrer, original_url)
WITH src AS (
    SELECT
        appsflyer_hashkey,
        source_event_date,
        city,
        wifi,
        operator,
        language,
        advertising_id,
        idfa,
        android_id,
        customer_user_id,
        imei,
        idfv,
        platform,
        device_type,
        os_version,
        app_version,
        sdk_version,
        app_id,
        app_name,
        bundle_id,
        country_code,
        dma,
        ip,
        postal_code,
        region,
        state,
        user_agent,
        http_referrer,
        original_url
    FROM tmp_organic_in_app_events_report
),
delta AS (
    SELECT * FROM src
    EXCEPT ALL
    SELECT
        appsflyer_hashkey,
        source_event_date,
        city,
        wifi,
        operator,
        language,
        advertising_id,
        idfa,
        android_id,
        customer_user_id,
        imei,
        idfv,
        platform,
        device_type,
        os_version,
        app_version,
        sdk_version,
        app_id,
        app_name,
        bundle_id,
        country_code,
        dma,
        ip,
        postal_code,
        region,
        state,
        user_agent,
        http_referrer,
        original_url
    FROM IDENTIFIER({{catalog_cleaned}} || '.raw_vault.non_his_sat_organic_in_app_events_device')
    WHERE source_event_date BETWEEN to_date({{start_date}}, 'yyyyMMdd') AND to_date({{end_date}}, 'yyyyMMdd')
)
SELECT
    d.appsflyer_hashkey AS appsflyer_hashkey,
    d.source_event_date AS source_event_date,
    current_timestamp() AS load_timestamp,
    'appsflyer__organic_in_app_events_report' AS record_source,
    d.city AS city,
    d.wifi AS wifi,
    d.operator AS operator,
    d.language AS language,
    d.advertising_id AS advertising_id,
    d.idfa AS idfa,
    d.android_id AS android_id,
    d.customer_user_id AS customer_user_id,
    d.imei AS imei,
    d.idfv AS idfv,
    d.platform AS platform,
    d.device_type AS device_type,
    d.os_version AS os_version,
    d.app_version AS app_version,
    d.sdk_version AS sdk_version,
    d.app_id AS app_id,
    d.app_name AS app_name,
    d.bundle_id AS bundle_id,
    d.country_code AS country_code,
    d.dma AS dma,
    d.ip AS ip,
    d.postal_code AS postal_code,
    d.region AS region,
    d.state AS state,
    d.user_agent AS user_agent,
    d.http_referrer AS http_referrer,
    d.original_url AS original_url
FROM delta d;

DROP TEMPORARY TABLE IF EXISTS tmp_organic_in_app_events_report;
