{{ config(
    alias = 'sat_giao_dich_ttd_igen',
    materialized = 'incremental_checkpoint',
    incremental_strategy = 'merge',
    unique_key = ['giao_dich_hashkey', 'id', 'hashdiff', 'source_event_date'],
    skip_matched_step = true,
    tags = ['bpm', 'phase2', 'all']
) }}

{% set source_name = 'bpm' %}
{% set source_table = 'ttd_giao_dich_igen' %}
{% set hashdiff_col = 'hashdiff_giao_dich_ttd_igen' %}
{% set hub_hashkey = 'giao_dich_hashkey' %}
{% set source_model = 'v_stg_bpm_ttd_giao_dich_igen' %}
{% set list_cols = [
    'id',
    'refnewfo',
    'khach_hang_id',
    'tenkhachhang',
    'cif',
    'ngaysinh',
    'gioitinh',
    'sogiaytotuythan',
    'ngaycap',
    'noicap',
    'sodienthoai',
    'email',
    'quoctich',
    'hokhauthuongtru',
    'noiohientai',
    'xhtd',
    'nhomcskhomni',
    'hanmucdexuat',
    'hanmucpheduyet',
    'tenintrenthe',
    'chiphisinhhoat',
    'chiphitranotctdkhac',
    'tinhtrangnghenghiep',
    'chucvu',
    'ascore',
    'bscore',
    'loaithechitietdexuat',
    'loaithedexuat',
    'nghiepvuchitiet',
    'doituongkh',
    'nhomcskhchung',
    'nhomcskhchitiet',
    'ngay_tao',
    'user_tao',
    'trang_thai',
    'hinhthucbaodam',
    'tinhtranghonnhan',
    'giatritsbd',
    'trangthaithe',
    'matsbd',
    'mahm',
    'hmthe',
    'donvitiente',
    'sothe',
    'sanphamthe',
    'ngoithamdinh',
    'donvipht',
    'loaithew4',
    'tenkhachhangdoitac',
    'gtttdoitac',
    'sdtdoitac',
    'thunhapchiuthuedoitac',
    'loaikhomni',
    'gtttcu',
    'hanmuckhhh',
    'hm_thethamchieu',
    'dunobinhquan_6t',
    'tyleduno_thoidiemxetcap',
    'solantongduno',
    'tong_hm_the',
    'ma_chi_nhanh',
    'ngaykhdexuat',
    'ngaypheduyetyeccaumothe',
    'ngaybatdauhm',
    'ngayketthuchm',
    'banghoitin',
    'hinhanh',
    'source',
    'tong_thu_nhap',
    'loaithepheduyet',
    'loaithechitietpheduyet',
    'ketquaaml',
    'thethamchieu'
] %}
{% set raw_sql = None %}

{{ satellite(
    source_model=source_model,
    source_name=source_name,
    source_table=source_table,
    hub_hashkey=hub_hashkey,
    hashdiff_name=hashdiff_col,
    list_cols=list_cols
) }}
